# Generated by Django 3.2.9 on 2022-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_courses_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
