# Generated by Django 3.2.9 on 2022-03-26 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20220224_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_price', models.IntegerField(default=0)),
                ('price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan_ends_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
