# Generated by Django 3.2.9 on 2022-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_recurring_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
