# Generated by Django 3.2.9 on 2022-03-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_plans_plan_recurring_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_price',
            field=models.FloatField(default=0),
        ),
    ]
