# Generated by Django 3.2.9 on 2022-03-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20220326_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.parents')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.plans')),
            ],
        ),
    ]
